## Bappy Ahmed

In [3]:
import pandas as pd
import pymongo

In [63]:

client = pymongo.MongoClient("mongodb+srv://bappy:bappy73@cluster0.zrfek.mongodb.net/passengerinfo?retryWrites=true&w=majority")
db = client.test
print('ok')

ok

# Data inseting in MongoDB Atlas

In [58]:

CONNECTION_URL = "mongodb+srv://bappy:bappy73@cluster0.zrfek.mongodb.net/passengerinfo?retryWrites=true&w=majority"

# Fetching Data

In [52]:
url = 'https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv'

df = pd.read_csv(url, sep='\t')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [53]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [59]:
import numpy as np
arr = np.array(df)

In [61]:
DB_NAME = "Titanic" # Specifiy a Database Name
# Establish a connection with mongoDB Atlas
client = pymongo.MongoClient(CONNECTION_URL)

# Create a DB
dataBase = client[DB_NAME]

# Create a Collection Name
COLLECTION_NAME = "info"
collection = dataBase[COLLECTION_NAME]

#inserting data
for info in arr:
    val = info
#     print(i)
    PassengerId = val[0]
    Survived = val[1]
    Pclass =val[2]
    Name = val[3]
    Sex = val[4]
    Age = val[5]
    SibSp =val[6]
    Parch =val[7]
    Ticket = val[8] 
    Fare = val[9]
    Cabin = val[10]
    Embarked = val[11]
        

    records = {'PassengerId':PassengerId, 
               'Survived': Survived, 
               'Pclass':Pclass, 
               'Name': Name, 
               'Sex': Sex, 
               'Age': Age, 
               'SibSp':SibSp,
               'Parch':Parch, 
               'Ticket': Ticket, 
               'Fare': Fare, 
               'Cabin': Cabin, 
               'Embarked': Embarked}
          

    collection.insert_one(records)

In [62]:
all_record = collection.find()
for info in all_record:
    print(info)

{'_id': ObjectId('60e36cb30b807fd04b783dac'), 'PassengerId': 1, 'Survived': 0, 'Pclass': 3, 'Name': 'Braund, Mr. Owen Harris', 'Sex': 'male', 'Age': 22.0, 'SibSp': 1, 'Parch': 0, 'Ticket': 'A/5 21171', 'Fare': 7.25, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb50b807fd04b783dad'), 'PassengerId': 2, 'Survived': 1, 'Pclass': 1, 'Name': 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'Sex': 'female', 'Age': 38.0, 'SibSp': 1, 'Parch': 0, 'Ticket': 'PC 17599', 'Fare': 71.2833, 'Cabin': 'C85', 'Embarked': 'C'}
{'_id': ObjectId('60e36cb50b807fd04b783dae'), 'PassengerId': 3, 'Survived': 1, 'Pclass': 3, 'Name': 'Heikkinen, Miss. Laina', 'Sex': 'female', 'Age': 26.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'STON/O2. 3101282', 'Fare': 7.925, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb60b807fd04b783daf'), 'PassengerId': 4, 'Survived': 1, 'Pclass': 1, 'Name': 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 'Sex': 'female', 'Age': 35.0, 'SibSp': 1, 'Parch': 0, 'Ticket': '113803', 'Fare': 53.1, 'Cabin': 'C123', 'Embarked': 'S'}
{'_id': ObjectId('60e36cb60b807fd04b783db0'), 'PassengerId': 5, 'Survived': 0, 'Pclass': 3, 'Name': 'Allen, Mr. William Henry', 'Sex': 'male', 'Age': 35.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '373450', 'Fare': 8.05, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb60b807fd04b783db1'), 'PassengerId': 6, 'Survived': 0, 'Pclass': 3, 'Name': 'Moran, Mr. James', 'Sex': 'male', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': '330877', 'Fare': 8.4583, 'Cabin': nan, 'Embarked': 'Q'}
{'_id': ObjectId('60e36cb60b807fd04b783db2'), 'PassengerId': 7, 'Survived': 0, 'Pclass': 1, 'Name': 'McCarthy, Mr. Timothy J', 'Sex': 'male', 'Age': 54.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '17463', 'Fare': 51.8625, 'Cabin': 'E46', 'Embarked': 'S'}
{'_id': ObjectId('60e36cb60b807fd04b783db3'), 'PassengerId': 8, 'Survived': 0, 'Pclass': 3, 'Name': 'Palsson, Master. Gosta Leonard', 'Sex': 'male', 'Age': 2.0, 'SibSp': 3, 'Parch': 1, 'Ticket': '349909', 'Fare': 21.075, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb60b807fd04b783db4'), 'PassengerId': 9, 'Survived': 1, 'Pclass': 3, 'Name': 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)', 'Sex': 'female', 'Age': 27.0, 'SibSp': 0, 'Parch': 2, 'Ticket': '347742', 'Fare': 11.1333, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb60b807fd04b783db5'), 'PassengerId': 10, 'Survived': 1, 'Pclass': 2, 'Name': 'Nasser, Mrs. Nicholas (Adele Achem)', 'Sex': 'female', 'Age': 14.0, 'SibSp': 1, 'Parch': 0, 'Ticket': '237736', 'Fare': 30.0708, 'Cabin': nan, 'Embarked': 'C'}
{'_id': ObjectId('60e36cb60b807fd04b783db6'), 'PassengerId': 11, 'Survived': 1, 'Pclass': 3, 'Name': 'Sandstrom, Miss. Marguerite Rut', 'Sex': 'female', 'Age': 4.0, 'SibSp': 1, 'Parch': 1, 'Ticket': 'PP 9549', 'Fare': 16.7, 'Cabin': 'G6', 'Embarked': 'S'}
{'_id': ObjectId('60e36cb60b807fd04b783db7'), 'PassengerId': 12, 'Survived': 1, 'Pclass': 1, 'Name': 'Bonnell, Miss. Elizabeth', 'Sex': 'female', 'Age': 58.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '113783', 'Fare': 26.55, 'Cabin': 'C103', 'Embarked': 'S'}
{'_id': ObjectId('60e36cb60b807fd04b783db8'), 'PassengerId': 13, 'Survived': 0, 'Pclass': 3, 'Name': 'Saundercock, Mr. William Henry', 'Sex': 'male', 'Age': 20.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'A/5. 2151', 'Fare': 8.05, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb60b807fd04b783db9'), 'PassengerId': 14, 'Survived': 0, 'Pclass': 3, 'Name': 'Andersson, Mr. Anders Johan', 'Sex': 'male', 'Age': 39.0, 'SibSp': 1, 'Parch': 5, 'Ticket': '347082', 'Fare': 31.275, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb60b807fd04b783dba'), 'PassengerId': 15, 'Survived': 0, 'Pclass': 3, 'Name': 'Vestrom, Miss. Hulda Amanda Adolfina', 'Sex': 'female', 'Age': 14.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '350406', 'Fare': 7.8542, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb60b807fd04b783dbb'), 'PassengerId': 16, 'Survived': 1, 'Pclass': 2, 'Name': 'Hewlett, Mrs. (Mary D Kingcome) ', 'Sex': 'female', 'Age': 55.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '248706', 'Fare': 16.0, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb60b807fd04b783dbc'), 'PassengerId': 17, 'Survived': 0, 'Pclass': 3, 'Name': 'Rice, Master. Eugene', 'Sex': 'male', 'Age': 2.0, 'SibSp': 4, 'Parch': 1, 'Ticket': '382652', 'Fare': 29.125, 'Cabin': nan, 'Embarked': 'Q'}
{'_id': ObjectId('60e36cb60b807fd04b783dbd'), 'PassengerId': 18, 'Survived': 1, 'Pclass': 2, 'Name': 'Williams, Mr. Charles Eugene', 'Sex': 'male', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': '244373', 'Fare': 13.0, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb60b807fd04b783dbe'), 'PassengerId': 19, 'Survived': 0, 'Pclass': 3, 'Name': 'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)', 'Sex': 'female', 'Age': 31.0, 'SibSp': 1, 'Parch': 0, 'Ticket': '345763', 'Fare': 18.0, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb60b807fd04b783dbf'), 'PassengerId': 20, 'Survived': 1, 'Pclass': 3, 'Name': 'Masselmani, Mrs. Fatima', 'Sex': 'female', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': '2649', 'Fare': 7.225, 'Cabin': nan, 'Embarked': 'C'}
{'_id': ObjectId('60e36cb60b807fd04b783dc0'), 'PassengerId': 21, 'Survived': 0, 'Pclass': 2, 'Name': 'Fynney, Mr. Joseph J', 'Sex': 'male', 'Age': 35.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '239865', 'Fare': 26.0, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb60b807fd04b783dc1'), 'PassengerId': 22, 'Survived': 1, 'Pclass': 2, 'Name': 'Beesley, Mr. Lawrence', 'Sex': 'male', 'Age': 34.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '248698', 'Fare': 13.0, 'Cabin': 'D56', 'Embarked': 'S'}
{'_id': ObjectId('60e36cb70b807fd04b783dc2'), 'PassengerId': 23, 'Survived': 1, 'Pclass': 3, 'Name': 'McGowan, Miss. Anna "Annie"', 'Sex': 'female', 'Age': 15.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '330923', 'Fare': 8.0292, 'Cabin': nan, 'Embarked': 'Q'}
{'_id': ObjectId('60e36cb70b807fd04b783dc3'), 'PassengerId': 24, 'Survived': 1, 'Pclass': 1, 'Name': 'Sloper, Mr. William Thompson', 'Sex': 'male', 'Age': 28.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '113788', 'Fare': 35.5, 'Cabin': 'A6', 'Embarked': 'S'}
{'_id': ObjectId('60e36cb70b807fd04b783dc4'), 'PassengerId': 25, 'Survived': 0, 'Pclass': 3, 'Name': 'Palsson, Miss. Torborg Danira', 'Sex': 'female', 'Age': 8.0, 'SibSp': 3, 'Parch': 1, 'Ticket': '349909', 'Fare': 21.075, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb70b807fd04b783dc5'), 'PassengerId': 26, 'Survived': 1, 'Pclass': 3, 'Name': 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)', 'Sex': 'female', 'Age': 38.0, 'SibSp': 1, 'Parch': 5, 'Ticket': '347077', 'Fare': 31.3875, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb70b807fd04b783dc6'), 'PassengerId': 27, 'Survived': 0, 'Pclass': 3, 'Name': 'Emir, Mr. Farred Chehab', 'Sex': 'male', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': '2631', 'Fare': 7.225, 'Cabin': nan, 'Embarked': 'C'}
{'_id': ObjectId('60e36cb70b807fd04b783dc7'), 'PassengerId': 28, 'Survived': 0, 'Pclass': 1, 'Name': 'Fortune, Mr. Charles Alexander', 'Sex': 'male', 'Age': 19.0, 'SibSp': 3, 'Parch': 2, 'Ticket': '19950', 'Fare': 263.0, 'Cabin': 'C23 C25 C27', 'Embarked': 'S'}
{'_id': ObjectId('60e36cb70b807fd04b783dc8'), 'PassengerId': 29, 'Survived': 1, 'Pclass': 3, 'Name': 'O\'Dwyer, Miss. Ellen "Nellie"', 'Sex': 'female', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': '330959', 'Fare': 7.8792, 'Cabin': nan, 'Embarked': 'Q'}
{'_id': ObjectId('60e36cb70b807fd04b783dc9'), 'PassengerId': 30, 'Survived': 0, 'Pclass': 3, 'Name': 'Todoroff, Mr. Lalio', 'Sex': 'male', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': '349216', 'Fare': 7.8958, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb70b807fd04b783dca'), 'PassengerId': 31, 'Survived': 0, 'Pclass': 1, 'Name': 'Uruchurtu, Don. Manuel E', 'Sex': 'male', 'Age': 40.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'PC 17601', 'Fare': 27.7208, 'Cabin': nan, 'Embarked': 'C'}
{'_id': ObjectId('60e36cb70b807fd04b783dcb'), 'PassengerId': 32, 'Survived': 1, 'Pclass': 1, 'Name': 'Spencer, Mrs. William Augustus (Marie Eugenie)', 'Sex': 'female', 'Age': nan, 'SibSp': 1, 'Parch': 0, 'Ticket': 'PC 17569', 'Fare': 146.5208, 'Cabin': 'B78', 'Embarked': 'C'}
{'_id': ObjectId('60e36cb70b807fd04b783dcc'), 'PassengerId': 33, 'Survived': 1, 'Pclass': 3, 'Name': 'Glynn, Miss. Mary Agatha', 'Sex': 'female', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': '335677', 'Fare': 7.75, 'Cabin': nan, 'Embarked': 'Q'}
{'_id': ObjectId('60e36cb70b807fd04b783dcd'), 'PassengerId': 34, 'Survived': 0, 'Pclass': 2, 'Name': 'Wheadon, Mr. Edward H', 'Sex': 'male', 'Age': 66.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'C.A. 24579', 'Fare': 10.5, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb70b807fd04b783dce'), 'PassengerId': 35, 'Survived': 0, 'Pclass': 1, 'Name': 'Meyer, Mr. Edgar Joseph', 'Sex': 'male', 'Age': 28.0, 'SibSp': 1, 'Parch': 0, 'Ticket': 'PC 17604', 'Fare': 82.1708, 'Cabin': nan, 'Embarked': 'C'}
{'_id': ObjectId('60e36cb70b807fd04b783dcf'), 'PassengerId': 36, 'Survived': 0, 'Pclass': 1, 'Name': 'Holverson, Mr. Alexander Oskar', 'Sex': 'male', 'Age': 42.0, 'SibSp': 1, 'Parch': 0, 'Ticket': '113789', 'Fare': 52.0, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb70b807fd04b783dd0'), 'PassengerId': 37, 'Survived': 1, 'Pclass': 3, 'Name': 'Mamee, Mr. Hanna', 'Sex': 'male', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': '2677', 'Fare': 7.2292, 'Cabin': nan, 'Embarked': 'C'}
{'_id': ObjectId('60e36cb70b807fd04b783dd1'), 'PassengerId': 38, 'Survived': 0, 'Pclass': 3, 'Name': 'Cann, Mr. Ernest Charles', 'Sex': 'male', 'Age': 21.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'A./5. 2152', 'Fare': 8.05, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb70b807fd04b783dd2'), 'PassengerId': 39, 'Survived': 0, 'Pclass': 3, 'Name': 'Vander Planke, Miss. Augusta Maria', 'Sex': 'female', 'Age': 18.0, 'SibSp': 2, 'Parch': 0, 'Ticket': '345764', 'Fare': 18.0, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb70b807fd04b783dd3'), 'PassengerId': 40, 'Survived': 1, 'Pclass': 3, 'Name': 'Nicola-Yarred, Miss. Jamila', 'Sex': 'female', 'Age': 14.0, 'SibSp': 1, 'Parch': 0, 'Ticket': '2651', 'Fare': 11.2417, 'Cabin': nan, 'Embarked': 'C'}
{'_id': ObjectId('60e36cb70b807fd04b783dd4'), 'PassengerId': 41, 'Survived': 0, 'Pclass': 3, 'Name': 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)', 'Sex': 'female', 'Age': 40.0, 'SibSp': 1, 'Parch': 0, 'Ticket': '7546', 'Fare': 9.475, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb80b807fd04b783dd5'), 'PassengerId': 42, 'Survived': 0, 'Pclass': 2, 'Name': 'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)', 'Sex': 'female', 'Age': 27.0, 'SibSp': 1, 'Parch': 0, 'Ticket': '11668', 'Fare': 21.0, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb80b807fd04b783dd6'), 'PassengerId': 43, 'Survived': 0, 'Pclass': 3, 'Name': 'Kraeff, Mr. Theodor', 'Sex': 'male', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': '349253', 'Fare': 7.8958, 'Cabin': nan, 'Embarked': 'C'}
{'_id': ObjectId('60e36cb80b807fd04b783dd7'), 'PassengerId': 44, 'Survived': 1, 'Pclass': 2, 'Name': 'Laroche, Miss. Simonne Marie Anne Andree', 'Sex': 'female', 'Age': 3.0, 'SibSp': 1, 'Parch': 2, 'Ticket': 'SC/Paris 2123', 'Fare': 41.5792, 'Cabin': nan, 'Embarked': 'C'}
{'_id': ObjectId('60e36cb80b807fd04b783dd8'), 'PassengerId': 45, 'Survived': 1, 'Pclass': 3, 'Name': 'Devaney, Miss. Margaret Delia', 'Sex': 'female', 'Age': 19.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '330958', 'Fare': 7.8792, 'Cabin': nan, 'Embarked': 'Q'}
{'_id': ObjectId('60e36cb80b807fd04b783dd9'), 'PassengerId': 46, 'Survived': 0, 'Pclass': 3, 'Name': 'Rogers, Mr. William John', 'Sex': 'male', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': 'S.C./A.4. 23567', 'Fare': 8.05, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb80b807fd04b783dda'), 'PassengerId': 47, 'Survived': 0, 'Pclass': 3, 'Name': 'Lennon, Mr. Denis', 'Sex': 'male', 'Age': nan, 'SibSp': 1, 'Parch': 0, 'Ticket': '370371', 'Fare': 15.5, 'Cabin': nan, 'Embarked': 'Q'}
{'_id': ObjectId('60e36cb80b807fd04b783ddb'), 'PassengerId': 48, 'Survived': 1, 'Pclass': 3, 'Name': "O'Driscoll, Miss. Bridget", 'Sex': 'female', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': '14311', 'Fare': 7.75, 'Cabin': nan, 'Embarked': 'Q'}
{'_id': ObjectId('60e36cb80b807fd04b783ddc'), 'PassengerId': 49, 'Survived': 0, 'Pclass': 3, 'Name': 'Samaan, Mr. Youssef', 'Sex': 'male', 'Age': nan, 'SibSp': 2, 'Parch': 0, 'Ticket': '2662', 'Fare': 21.6792, 'Cabin': nan, 'Embarked': 'C'}
{'_id': ObjectId('60e36cb80b807fd04b783ddd'), 'PassengerId': 50, 'Survived': 0, 'Pclass': 3, 'Name': 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)', 'Sex': 'female', 'Age': 18.0, 'SibSp': 1, 'Parch': 0, 'Ticket': '349237', 'Fare': 17.8, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb80b807fd04b783dde'), 'PassengerId': 51, 'Survived': 0, 'Pclass': 3, 'Name': 'Panula, Master. Juha Niilo', 'Sex': 'male', 'Age': 7.0, 'SibSp': 4, 'Parch': 1, 'Ticket': '3101295', 'Fare': 39.6875, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb80b807fd04b783ddf'), 'PassengerId': 52, 'Survived': 0, 'Pclass': 3, 'Name': 'Nosworthy, Mr. Richard Cater', 'Sex': 'male', 'Age': 21.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'A/4. 39886', 'Fare': 7.8, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb80b807fd04b783de0'), 'PassengerId': 53, 'Survived': 1, 'Pclass': 1, 'Name': 'Harper, Mrs. Henry Sleeper (Myna Haxtun)', 'Sex': 'female', 'Age': 49.0, 'SibSp': 1, 'Parch': 0, 'Ticket': 'PC 17572', 'Fare': 76.7292, 'Cabin': 'D33', 'Embarked': 'C'}
{'_id': ObjectId('60e36cb80b807fd04b783de1'), 'PassengerId': 54, 'Survived': 1, 'Pclass': 2, 'Name': 'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)', 'Sex': 'female', 'Age': 29.0, 'SibSp': 1, 'Parch': 0, 'Ticket': '2926', 'Fare': 26.0, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb80b807fd04b783de2'), 'PassengerId': 55, 'Survived': 0, 'Pclass': 1, 'Name': 'Ostby, Mr. Engelhart Cornelius', 'Sex': 'male', 'Age': 65.0, 'SibSp': 0, 'Parch': 1, 'Ticket': '113509', 'Fare': 61.9792, 'Cabin': 'B30', 'Embarked': 'C'}
{'_id': ObjectId('60e36cb80b807fd04b783de3'), 'PassengerId': 56, 'Survived': 1, 'Pclass': 1, 'Name': 'Woolner, Mr. Hugh', 'Sex': 'male', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': '19947', 'Fare': 35.5, 'Cabin': 'C52', 'Embarked': 'S'}
{'_id': ObjectId('60e36cb80b807fd04b783de4'), 'PassengerId': 57, 'Survived': 1, 'Pclass': 2, 'Name': 'Rugg, Miss. Emily', 'Sex': 'female', 'Age': 21.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'C.A. 31026', 'Fare': 10.5, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb80b807fd04b783de5'), 'PassengerId': 58, 'Survived': 0, 'Pclass': 3, 'Name': 'Novel, Mr. Mansouer', 'Sex': 'male', 'Age': 28.5, 'SibSp': 0, 'Parch': 0, 'Ticket': '2697', 'Fare': 7.2292, 'Cabin': nan, 'Embarked': 'C'}
{'_id': ObjectId('60e36cb80b807fd04b783de6'), 'PassengerId': 59, 'Survived': 1, 'Pclass': 2, 'Name': 'West, Miss. Constance Mirium', 'Sex': 'female', 'Age': 5.0, 'SibSp': 1, 'Parch': 2, 'Ticket': 'C.A. 34651', 'Fare': 27.75, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb80b807fd04b783de7'), 'PassengerId': 60, 'Survived': 0, 'Pclass': 3, 'Name': 'Goodwin, Master. William Frederick', 'Sex': 'male', 'Age': 11.0, 'SibSp': 5, 'Parch': 2, 'Ticket': 'CA 2144', 'Fare': 46.9, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb90b807fd04b783de8'), 'PassengerId': 61, 'Survived': 0, 'Pclass': 3, 'Name': 'Sirayanian, Mr. Orsen', 'Sex': 'male', 'Age': 22.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '2669', 'Fare': 7.2292, 'Cabin': nan, 'Embarked': 'C'}
{'_id': ObjectId('60e36cb90b807fd04b783de9'), 'PassengerId': 62, 'Survived': 1, 'Pclass': 1, 'Name': 'Icard, Miss. Amelie', 'Sex': 'female', 'Age': 38.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '113572', 'Fare': 80.0, 'Cabin': 'B28', 'Embarked': nan}
{'_id': ObjectId('60e36cb90b807fd04b783dea'), 'PassengerId': 63, 'Survived': 0, 'Pclass': 1, 'Name': 'Harris, Mr. Henry Birkhardt', 'Sex': 'male', 'Age': 45.0, 'SibSp': 1, 'Parch': 0, 'Ticket': '36973', 'Fare': 83.475, 'Cabin': 'C83', 'Embarked': 'S'}
{'_id': ObjectId('60e36cb90b807fd04b783deb'), 'PassengerId': 64, 'Survived': 0, 'Pclass': 3, 'Name': 'Skoog, Master. Harald', 'Sex': 'male', 'Age': 4.0, 'SibSp': 3, 'Parch': 2, 'Ticket': '347088', 'Fare': 27.9, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb90b807fd04b783dec'), 'PassengerId': 65, 'Survived': 0, 'Pclass': 1, 'Name': 'Stewart, Mr. Albert A', 'Sex': 'male', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': 'PC 17605', 'Fare': 27.7208, 'Cabin': nan, 'Embarked': 'C'}
{'_id': ObjectId('60e36cb90b807fd04b783ded'), 'PassengerId': 66, 'Survived': 1, 'Pclass': 3, 'Name': 'Moubarek, Master. Gerios', 'Sex': 'male', 'Age': nan, 'SibSp': 1, 'Parch': 1, 'Ticket': '2661', 'Fare': 15.2458, 'Cabin': nan, 'Embarked': 'C'}
{'_id': ObjectId('60e36cb90b807fd04b783dee'), 'PassengerId': 67, 'Survived': 1, 'Pclass': 2, 'Name': 'Nye, Mrs. (Elizabeth Ramell)', 'Sex': 'female', 'Age': 29.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'C.A. 29395', 'Fare': 10.5, 'Cabin': 'F33', 'Embarked': 'S'}
{'_id': ObjectId('60e36cb90b807fd04b783def'), 'PassengerId': 68, 'Survived': 0, 'Pclass': 3, 'Name': 'Crease, Mr. Ernest James', 'Sex': 'male', 'Age': 19.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'S.P. 3464', 'Fare': 8.1583, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb90b807fd04b783df0'), 'PassengerId': 69, 'Survived': 1, 'Pclass': 3, 'Name': 'Andersson, Miss. Erna Alexandra', 'Sex': 'female', 'Age': 17.0, 'SibSp': 4, 'Parch': 2, 'Ticket': '3101281', 'Fare': 7.925, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb90b807fd04b783df1'), 'PassengerId': 70, 'Survived': 0, 'Pclass': 3, 'Name': 'Kink, Mr. Vincenz', 'Sex': 'male', 'Age': 26.0, 'SibSp': 2, 'Parch': 0, 'Ticket': '315151', 'Fare': 8.6625, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb90b807fd04b783df2'), 'PassengerId': 71, 'Survived': 0, 'Pclass': 2, 'Name': 'Jenkin, Mr. Stephen Curnow', 'Sex': 'male', 'Age': 32.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'C.A. 33111', 'Fare': 10.5, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cb90b807fd04b783df3'), 'PassengerId': 72, 'Survived': 0, 'Pclass': 3, 'Name': 'Goodwin, Miss. Lillian Amy', 'Sex': 'female', 'Age': 16.0, 'SibSp': 5, 'Parch': 2, 'Ticket': 'CA 2144', 'Fare': 46.9, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cba0b807fd04b783df4'), 'PassengerId': 73, 'Survived': 0, 'Pclass': 2, 'Name': 'Hood, Mr. Ambrose Jr', 'Sex': 'male', 'Age': 21.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'S.O.C. 14879', 'Fare': 73.5, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cba0b807fd04b783df5'), 'PassengerId': 74, 'Survived': 0, 'Pclass': 3, 'Name': 'Chronopoulos, Mr. Apostolos', 'Sex': 'male', 'Age': 26.0, 'SibSp': 1, 'Parch': 0, 'Ticket': '2680', 'Fare': 14.4542, 'Cabin': nan, 'Embarked': 'C'}
{'_id': ObjectId('60e36cba0b807fd04b783df6'), 'PassengerId': 75, 'Survived': 1, 'Pclass': 3, 'Name': 'Bing, Mr. Lee', 'Sex': 'male', 'Age': 32.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '1601', 'Fare': 56.4958, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cba0b807fd04b783df7'), 'PassengerId': 76, 'Survived': 0, 'Pclass': 3, 'Name': 'Moen, Mr. Sigurd Hansen', 'Sex': 'male', 'Age': 25.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '348123', 'Fare': 7.65, 'Cabin': 'F G73', 'Embarked': 'S'}
{'_id': ObjectId('60e36cbb0b807fd04b783df8'), 'PassengerId': 77, 'Survived': 0, 'Pclass': 3, 'Name': 'Staneff, Mr. Ivan', 'Sex': 'male', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': '349208', 'Fare': 7.8958, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cbb0b807fd04b783df9'), 'PassengerId': 78, 'Survived': 0, 'Pclass': 3, 'Name': 'Moutal, Mr. Rahamin Haim', 'Sex': 'male', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': '374746', 'Fare': 8.05, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cbb0b807fd04b783dfa'), 'PassengerId': 79, 'Survived': 1, 'Pclass': 2, 'Name': 'Caldwell, Master. Alden Gates', 'Sex': 'male', 'Age': 0.83, 'SibSp': 0, 'Parch': 2, 'Ticket': '248738', 'Fare': 29.0, 'Cabin': nan, 'Embarked': 'S'}

{'_id': ObjectId('60e36cbc0b807fd04b783e11'), 'PassengerId': 102, 'Survived': 0, 'Pclass': 3, 'Name': 'Petroff, Mr. Pastcho ("Pentcho")', 'Sex': 'male', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': '349215', 'Fare': 7.8958, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cbc0b807fd04b783e12'), 'PassengerId': 103, 'Survived': 0, 'Pclass': 1, 'Name': 'White, Mr. Richard Frasar', 'Sex': 'male', 'Age': 21.0, 'SibSp': 0, 'Parch': 1, 'Ticket': '35281', 'Fare': 77.2875, 'Cabin': 'D26', 'Embarked': 'S'}
{'_id': ObjectId('60e36cbc0b807fd04b783e13'), 'PassengerId': 104, 'Survived': 0, 'Pclass': 3, 'Name': 'Johansson, Mr. Gustaf Joel', 'Sex': 'male', 'Age': 33.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '7540', 'Fare': 8.6542, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cbc0b807fd04b783e14'), 'PassengerId': 105, 'Survived': 0, 'Pclass': 3, 'Name': 'Gustafsson, Mr. Anders Vilhelm', 'Sex': 'male', 'Age': 37.0, 'SibSp': 2, 'Parch': 0, 'Ticket': '3101276', 'Fare': 7.925, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cbc0b807fd04b783e15'), 'PassengerId': 106, 'Survived': 0, 'Pclass': 3, 'Name': 'Mionoff, Mr. Stoytcho', 'Sex': 'male', 'Age': 28.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '349207', 'Fare': 7.8958, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cbc0b807fd04b783e16'), 'PassengerId': 107, 'Survived': 1, 'Pclass': 3, 'Name': 'Salkjelsvik, Miss. Anna Kristine', 'Sex': 'female', 'Age': 21.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '343120', 'Fare': 7.65, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cbd0b807fd04b783e17'), 'PassengerId': 108, 'Survived': 1, 'Pclass': 3, 'Name': 'Moss, Mr. Albert Johan', 'Sex': 'male', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': '312991', 'Fare': 7.775, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cbd0b807fd04b783e18'), 'PassengerId': 109, 'Survived': 0, 'Pclass': 3, 'Name': 'Rekic, Mr. Tido', 'Sex': 'male', 'Age': 38.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '349249', 'Fare': 7.8958, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cbd0b807fd04b783e19'), 'PassengerId': 110, 'Survived': 1, 'Pclass': 3, 'Name': 'Moran, Miss. Bertha', 'Sex': 'female', 'Age': nan, 'SibSp': 1, 'Parch': 0, 'Ticket': '371110', 'Fare': 24.15, 'Cabin': nan, 'Embarked': 'Q'}
{'_id': ObjectId('60e36cbd0b807fd04b783e1a'), 'PassengerId': 111, 'Survived': 0, 'Pclass': 1, 'Name': 'Porter, Mr. Walter Chamberlain', 'Sex': 'male', 'Age': 47.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '110465', 'Fare': 52.0, 'Cabin': 'C110', 'Embarked': 'S'}
{'_id': ObjectId('60e36cbd0b807fd04b783e1b'), 'PassengerId': 112, 'Survived': 0, 'Pclass': 3, 'Name': 'Zabour, Miss. Hileni', 'Sex': 'female', 'Age': 14.5, 'SibSp': 1, 'Parch': 0, 'Ticket': '2665', 'Fare': 14.4542, 'Cabin': nan, 'Embarked': 'C'}
{'_id': ObjectId('60e36cbd0b807fd04b783e1c'), 'PassengerId': 113, 'Survived': 0, 'Pclass': 3, 'Name': 'Barton, Mr. David John', 'Sex': 'male', 'Age': 22.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '324669', 'Fare': 8.05, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cbd0b807fd04b783e1d'), 'PassengerId': 114, 'Survived': 0, 'Pclass': 3, 'Name': 'Jussila, Miss. Katriina', 'Sex': 'female', 'Age': 20.0, 'SibSp': 1, 'Parch': 0, 'Ticket': '4136', 'Fare': 9.825, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cbd0b807fd04b783e1e'), 'PassengerId': 115, 'Survived': 0, 'Pclass': 3, 'Name': 'Attalah, Miss. Malake', 'Sex': 'female', 'Age': 17.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '2627', 'Fare': 14.4583, 'Cabin': nan, 'Embarked': 'C'}
{'_id': ObjectId('60e36cbd0b807fd04b783e1f'), 'PassengerId': 116, 'Survived': 0, 'Pclass': 3, 'Name': 'Pekoniemi, Mr. Edvard', 'Sex': 'male', 'Age': 21.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'STON/O 2. 3101294', 'Fare': 7.925, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cbd0b807fd04b783e20'), 'PassengerId': 117, 'Survived': 0, 'Pclass': 3, 'Name': 'Connors, Mr. Patrick', 'Sex': 'male', 'Age': 70.5, 'SibSp': 0, 'Parch': 0, 'Ticket': '370369', 'Fare': 7.75, 'Cabin': nan, 'Embarked': 'Q'}
{'_id': ObjectId('60e36cbd0b807fd04b783e21'), 'PassengerId': 118, 'Survived': 0, 'Pclass': 2, 'Name': 'Turpin, Mr. William John Robert', 'Sex': 'male', 'Age': 29.0, 'SibSp': 1, 'Parch': 0, 'Ticket': '11668', 'Fare': 21.0, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cbd0b807fd04b783e22'), 'PassengerId': 119, 'Survived': 0, 'Pclass': 1, 'Name': 'Baxter, Mr. Quigg Edmond', 'Sex': 'male', 'Age': 24.0, 'SibSp': 0, 'Parch': 1, 'Ticket': 'PC 17558', 'Fare': 247.5208, 'Cabin': 'B58 B60', 'Embarked': 'C'}
{'_id': ObjectId('60e36cbd0b807fd04b783e23'), 'PassengerId': 120, 'Survived': 0, 'Pclass': 3, 'Name': 'Andersson, Miss. Ellis Anna Maria', 'Sex': 'female', 'Age': 2.0, 'SibSp': 4, 'Parch': 2, 'Ticket': '347082', 'Fare': 31.275, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cbe0b807fd04b783e24'), 'PassengerId': 121, 'Survived': 0, 'Pclass': 2, 'Name': 'Hickman, Mr. Stanley George', 'Sex': 'male', 'Age': 21.0, 'SibSp': 2, 'Parch': 0, 'Ticket': 'S.O.C. 14879', 'Fare': 73.5, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cbe0b807fd04b783e25'), 'PassengerId': 122, 'Survived': 0, 'Pclass': 3, 'Name': 'Moore, Mr. Leonard Charles', 'Sex': 'male', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': 'A4. 54510', 'Fare': 8.05, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cbe0b807fd04b783e26'), 'PassengerId': 123, 'Survived': 0, 'Pclass': 2, 'Name': 'Nasser, Mr. Nicholas', 'Sex': 'male', 'Age': 32.5, 'SibSp': 1, 'Parch': 0, 'Ticket': '237736', 'Fare': 30.0708, 'Cabin': nan, 'Embarked': 'C'}
{'_id': ObjectId('60e36cbf0b807fd04b783e27'), 'PassengerId': 124, 'Survived': 1, 'Pclass': 2, 'Name': 'Webber, Miss. Susan', 'Sex': 'female', 'Age': 32.5, 'SibSp': 0, 'Parch': 0, 'Ticket': '27267', 'Fare': 13.0, 'Cabin': 'E101', 'Embarked': 'S'}
{'_id': ObjectId('60e36cbf0b807fd04b783e28'), 'PassengerId': 125, 'Survived': 0, 'Pclass': 1, 'Name': 'White, Mr. Percival Wayland', 'Sex': 'male', 'Age': 54.0, 'SibSp': 0, 'Parch': 1, 'Ticket': '35281', 'Fare': 77.2875, 'Cabin': 'D26', 'Embarked': 'S'}
{'_id': ObjectId('60e36cbf0b807fd04b783e29'), 'PassengerId': 126, 'Survived': 1, 'Pclass': 3, 'Name': 'Nicola-Yarred, Master. Elias', 'Sex': 'male', 'Age': 12.0, 'SibSp': 1, 'Parch': 0, 'Ticket': '2651', 'Fare': 11.2417, 'Cabin': nan, 'Embarked': 'C'}
{'_id': ObjectId('60e36cbf0b807fd04b783e2a'), 'PassengerId': 127, 'Survived': 0, 'Pclass': 3, 'Name': 'McMahon, Mr. Martin', 'Sex': 'male', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': '370372', 'Fare': 7.75, 'Cabin': nan, 'Embarked': 'Q'}
{'_id': ObjectId('60e36cbf0b807fd04b783e2b'), 'PassengerId': 128, 'Survived': 1, 'Pclass': 3, 'Name': 'Madsen, Mr. Fridtjof Arne', 'Sex': 'male', 'Age': 24.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'C 17369', 'Fare': 7.1417, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cbf0b807fd04b783e2c'), 'PassengerId': 129, 'Survived': 1, 'Pclass': 3, 'Name': 'Peter, Miss. Anna', 'Sex': 'female', 'Age': nan, 'SibSp': 1, 'Parch': 1, 'Ticket': '2668', 'Fare': 22.3583, 'Cabin': 'F E69', 'Embarked': 'C'}
{'_id': ObjectId('60e36cbf0b807fd04b783e2d'), 'PassengerId': 130, 'Survived': 0, 'Pclass': 3, 'Name': 'Ekstrom, Mr. Johan', 'Sex': 'male', 'Age': 45.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '347061', 'Fare': 6.975, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cbf0b807fd04b783e2e'), 'PassengerId': 131, 'Survived': 0, 'Pclass': 3, 'Name': 'Drazenoic, Mr. Jozef', 'Sex': 'male', 'Age': 33.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '349241', 'Fare': 7.8958, 'Cabin': nan, 'Embarked': 'C'}
{'_id': ObjectId('60e36cbf0b807fd04b783e2f'), 'PassengerId': 132, 'Survived': 0, 'Pclass': 3, 'Name': 'Coelho, Mr. Domingos Fernandeo', 'Sex': 'male', 'Age': 20.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'SOTON/O.Q. 3101307', 'Fare': 7.05, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cbf0b807fd04b783e30'), 'PassengerId': 133, 'Survived': 0, 'Pclass': 3, 'Name': 'Robins, Mrs. Alexander A (Grace Charity Laury)', 'Sex': 'female', 'Age': 47.0, 'SibSp': 1, 'Parch': 0, 'Ticket': 'A/5. 3337', 'Fare': 14.5, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cc00b807fd04b783e31'), 'PassengerId': 134, 'Survived': 1, 'Pclass': 2, 'Name': 'Weisz, Mrs. Leopold (Mathilde Francoise Pede)', 'Sex': 'female', 'Age': 29.0, 'SibSp': 1, 'Parch': 0, 'Ticket': '228414', 'Fare': 26.0, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cc00b807fd04b783e32'), 'PassengerId': 135, 'Survived': 0, 'Pclass': 2, 'Name': 'Sobey, Mr. Samuel James Hayden', 'Sex': 'male', 'Age': 25.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'C.A. 29178', 'Fare': 13.0, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cc00b807fd04b783e33'), 'PassengerId': 136, 'Survived': 0, 'Pclass': 2, 'Name': 'Richard, Mr. Emile', 'Sex': 'male', 'Age': 23.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'SC/PARIS 2133', 'Fare': 15.0458, 'Cabin': nan, 'Embarked': 'C'}
{'_id': ObjectId('60e36cc00b807fd04b783e34'), 'PassengerId': 137, 'Survived': 1, 'Pclass': 1, 'Name': 'Newsom, Miss. Helen Monypeny', 'Sex': 'female', 'Age': 19.0, 'SibSp': 0, 'Parch': 2, 'Ticket': '11752', 'Fare': 26.2833, 'Cabin': 'D47', 'Embarked': 'S'}
{'_id': ObjectId('60e36cc00b807fd04b783e35'), 'PassengerId': 138, 'Survived': 0, 'Pclass': 1, 'Name': 'Futrelle, Mr. Jacques Heath', 'Sex': 'male', 'Age': 37.0, 'SibSp': 1, 'Parch': 0, 'Ticket': '113803', 'Fare': 53.1, 'Cabin': 'C123', 'Embarked': 'S'}
{'_id': ObjectId('60e36cc00b807fd04b783e36'), 'PassengerId': 139, 'Survived': 0, 'Pclass': 3, 'Name': 'Osen, Mr. Olaf Elon', 'Sex': 'male', 'Age': 16.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '7534', 'Fare': 9.2167, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cc00b807fd04b783e37'), 'PassengerId': 140, 'Survived': 0, 'Pclass': 1, 'Name': 'Giglio, Mr. Victor', 'Sex': 'male', 'Age': 24.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'PC 17593', 'Fare': 79.2, 'Cabin': 'B86', 'Embarked': 'C'}
{'_id': ObjectId('60e36cc00b807fd04b783e38'), 'PassengerId': 141, 'Survived': 0, 'Pclass': 3, 'Name': 'Boulos, Mrs. Joseph (Sultana)', 'Sex': 'female', 'Age': nan, 'SibSp': 0, 'Parch': 2, 'Ticket': '2678', 'Fare': 15.2458, 'Cabin': nan, 'Embarked': 'C'}
{'_id': ObjectId('60e36cc00b807fd04b783e39'), 'PassengerId': 142, 'Survived': 1, 'Pclass': 3, 'Name': 'Nysten, Miss. Anna Sofia', 'Sex': 'female', 'Age': 22.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '347081', 'Fare': 7.75, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cc00b807fd04b783e3a'), 'PassengerId': 143, 'Survived': 1, 'Pclass': 3, 'Name': 'Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)', 'Sex': 'female', 'Age': 24.0, 'SibSp': 1, 'Parch': 0, 'Ticket': 'STON/O2. 3101279', 'Fare': 15.85, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cc00b807fd04b783e3b'), 'PassengerId': 144, 'Survived': 0, 'Pclass': 3, 'Name': 'Burke, Mr. Jeremiah', 'Sex': 'male', 'Age': 19.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '365222', 'Fare': 6.75, 'Cabin': nan, 'Embarked': 'Q'}
{'_id': ObjectId('60e36cc00b807fd04b783e3c'), 'PassengerId': 145, 'Survived': 0, 'Pclass': 2, 'Name': 'Andrew, Mr. Edgardo Samuel', 'Sex': 'male', 'Age': 18.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '231945', 'Fare': 11.5, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cc00b807fd04b783e3d'), 'PassengerId': 146, 'Survived': 0, 'Pclass': 2, 'Name': 'Nicholls, Mr. Joseph Charles', 'Sex': 'male', 'Age': 19.0, 'SibSp': 1, 'Parch': 1, 'Ticket': 'C.A. 33112', 'Fare': 36.75, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cc00b807fd04b783e3e'), 'PassengerId': 147, 'Survived': 1, 'Pclass': 3, 'Name': 'Andersson, Mr. August Edvard ("Wennerstrom")', 'Sex': 'male', 'Age': 27.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '350043', 'Fare': 7.7958, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cc00b807fd04b783e3f'), 'PassengerId': 148, 'Survived': 0, 'Pclass': 3, 'Name': 'Ford, Miss. Robina Maggie "Ruby"', 'Sex': 'female', 'Age': 9.0, 'SibSp': 2, 'Parch': 2, 'Ticket': 'W./C. 6608', 'Fare': 34.375, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cc00b807fd04b783e40'), 'PassengerId': 149, 'Survived': 0, 'Pclass': 2, 'Name': 'Navratil, Mr. Michel ("Louis M Hoffman")', 'Sex': 'male', 'Age': 36.5, 'SibSp': 0, 'Parch': 2, 'Ticket': '230080', 'Fare': 26.0, 'Cabin': 'F2', 'Embarked': 'S'}
{'_id': ObjectId('60e36cc00b807fd04b783e41'), 'PassengerId': 150, 'Survived': 0, 'Pclass': 2, 'Name': 'Byles, Rev. Thomas Roussel Davids', 'Sex': 'male', 'Age': 42.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '244310', 'Fare': 13.0, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cc00b807fd04b783e42'), 'PassengerId': 151, 'Survived': 0, 'Pclass': 2, 'Name': 'Bateman, Rev. Robert James', 'Sex': 'male', 'Age': 51.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'S.O.P. 1166', 'Fare': 12.525, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cc00b807fd04b783e43'), 'PassengerId': 152, 'Survived': 1, 'Pclass': 1, 'Name': 'Pears, Mrs. Thomas (Edith Wearne)', 'Sex': 'female', 'Age': 22.0, 'SibSp': 1, 'Parch': 0, 'Ticket': '113776', 'Fare': 66.6, 'Cabin': 'C2', 'Embarked': 'S'}
{'_id': ObjectId('60e36cc10b807fd04b783e44'), 'PassengerId': 153, 'Survived': 0, 'Pclass': 3, 'Name': 'Meo, Mr. Alfonzo', 'Sex': 'male', 'Age': 55.5, 'SibSp': 0, 'Parch': 0, 'Ticket': 'A.5. 11206', 'Fare': 8.05, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cc10b807fd04b783e45'), 'PassengerId': 154, 'Survived': 0, 'Pclass': 3, 'Name': 'van Billiard, Mr. Austin Blyler', 'Sex': 'male', 'Age': 40.5, 'SibSp': 0, 'Parch': 2, 'Ticket': 'A/5. 851', 'Fare': 14.5, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cc10b807fd04b783e46'), 'PassengerId': 155, 'Survived': 0, 'Pclass': 3, 'Name': 'Olsen, Mr. Ole Martin', 'Sex': 'male', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': 'Fa 265302', 'Fare': 7.3125, 'Cabin': nan, 'Embarked': 'S'}
{'_id': ObjectId('60e36cc10b807fd04b783e47'), 'PassengerId': 156, 'Survived': 0, 'Pclass': 1, 'Name': 'Williams, Mr. Charles Duane', 'Sex': 'male', 'Age': 51.0, 'SibSp': 0, 'Parch': 1, 'Ticket': 'PC 17597', 'Fare': 61.3792, 'Cabin': nan, 'Embarked': 'C'}